config/routes.rb
Rails.application.eager_load! if Rails.env.development?

class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Peatio::Application.routes.draw do
  use_doorkeeper

  root 'welcome#index'

  if Rails.env.development?
    mount MailsViewer::Engine => '/mails'
  end

  get '/signin' => 'sessions#new', :as => :signin
  get '/signup' => 'identities#new', :as => :signup
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure', :as => :failure
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]

  resource :member, :only => [:edit, :update]
  resource :identity, :only => [:edit, :update]

  namespace :verify do
    resource :sms_auth,    only: [:show, :update]
    resource :google_auth, only: [:show, :update, :edit, :destroy]
  end

  namespace :authentications do
    resources :emails, only: [:new, :create]
    resources :identities, only: [:new, :create]
    resource :weibo_accounts, only: [:destroy]
  end

  scope :constraints => { id: /[a-zA-Z0-9]{32}/ } do
    resources :reset_passwords
    resources :activations, only: [:new, :edit, :update]
  end

  get '/documents/api_v2'
  get '/documents/websocket_api'
  get '/documents/oauth'
  get '/documents/price'
  get '/documents/wallet_maintainance'
  get '/documents/terms'
  get '/documents/license'
  get '/documents/txid_how'
  get '/documents/deposit_mock'
  resources :documents, only: [:show, :index]
  resources :two_factors, only: [:show, :index, :update]

  scope module: :private do
    resource  :id_document, only: [:edit, :update]

    resources :settings, only: [:index]
    resources :api_tokens do
      member do
        delete :unbind
      end
    end

    resources :fund_sources, only: [:create, :update, :destroy]

    resources :funds, only: [:index] do
      collection do
        post :gen_address
      end
    end

    namespace :deposits do
      Deposit.descendants.each do |d|
        resources d.resource_name do
          collection do
            post :gen_address
          end
        end
      end
    end

    namespace :withdraws do
      Withdraw.descendants.each do |w|
        resources w.resource_name
      end
    end

    resources :account_versions, :only => :index

    #resources :exchange_assets, :controller => 'assets' do
    #  member do
    #    get :partial_tree
    #  end
    #end

    get '/history/orders' => 'history#orders', as: :order_history
    get '/history/trades' => 'history#trades', as: :trade_history
    get '/history/account' => 'history#account', as: :account_history

    resources :markets, :only => :show, :constraints => MarketConstraint do
      resources :orders, :only => [:index, :destroy] do
        collection do
          post :clear
        end
      end
      resources :order_bids, :only => [:create] do
        collection do
          post :clear
        end
      end
      resources :order_asks, :only => [:create] do
        collection do
          post :clear
        end
      end
    end

    post '/pusher/auth', to: 'pusher#auth'

    resources :tickets, only: [:index, :new, :create, :show] do
      member do
        patch :close
      end
      resources :comments, only: [:create]
    end

    resources :self_services

  end
  post '/webhooks/btc' => 'webhooks#btc'
  post '/webhooks/eth' => 'webhooks#eth'
  post '/webhooks/ltc' => 'webhooks#ltc'
  get '/discoursesso' => 'discourse_sso#sso'

  draw :admin
  mount APIv2::Mount => APIv2::Mount::PREFIX

end

app/models/document.rb
class Document < ActiveRecord::Base
  TRANSLATABLE_ATTR = [:title, :desc, :keywords, :body]
  translates *TRANSLATABLE_ATTR

  def to_param
    self.key
  end

  TRANSLATABLE_ATTR.each do |attr|
    Rails.configuration.i18n.available_locales.each do |locale|
      locale = locale.to_s
      define_method "#{locale.underscore}_#{attr}=" do |value|
        with_locale locale do
          self.send("#{attr}=", value)
        end
      end

      define_method "#{locale.underscore}_#{attr}" do
        with_locale locale do
          self.send("#{attr}")
        end
      end
    end
  end

  def self.locale_params
    params = []
    TRANSLATABLE_ATTR.each do |attr|
      Rails.configuration.i18n.available_locales.each do |locale|
        locale = locale.to_s
        params << "#{locale.underscore}_#{attr}".to_sym
      end
    end
    params
  end

  private

  def with_locale locale
    original_locale = I18n.locale
    I18n.locale = locale
    value = yield if block_given?
    I18n.locale = original_locale
    value
  end
end

app/controllers/admin/documents_controller.rb
module Admin
  class DocumentsController < BaseController
    load_and_authorize_resource find_by: :key

    def index
      @documents_grid = ::DocumentsGrid.new(params[:documents_grid])
      @assets = @documents_grid.assets
    end

    def new
    end

    def create
      if @document.save
        redirect_to admin_documents_path
      else
        render :new
      end
    end

    def show
      render inline: @document.body.html_safe
    end

    def edit
    end

    def update
      if @document.update_attributes(document_params)
        redirect_to admin_documents_path
      else
        render :edit
      end
    end

    def destroy
    end

    private

    def document_params
      params.required(:document).permit(:key, :is_auth, *Document.locale_params)
    end

  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def index
    @docs ||= []

    #Hacky
    @docs << (Document.new(:key => 'price', title: t('document.price')))
    @docs << (Document.new(:key => 'api_v2', title: t('document.api_v2')))
    @docs << (Document.new(:key => 'wallet_maintainance', title: t('document.wallet_maintainance')))
    @docs << (Document.new(:key => 'txid_how', title: t('document.txid_how')))

    if current_user
      @docs += Document.all
    else
      @docs += Document.where.not(is_auth: true)
    end

  end

  def show
    @doc = Document.find_by_key(params[:id])
    raise ActiveRecord::RecordNotFound unless @doc

    if @doc.is_auth and !current_user
      redirect_to root_path, alert: t('activations.new.login_required')
    end
  end

  def api_v2
    render 'api_v2', layout: 'api_v2'
  end

  def websocket_api
    render 'websocket_api', layout: 'api_v2'
  end

  def oauth
    render 'oauth', layout: 'api_v2'
  end

  def price
    render 'price', layout: 'official_docs'
  end

  def wallet_maintainance
    render 'wallet_maintainance', layout: 'official_docs'
  end

  def terms
    render 'terms', layout: 'official_docs'
  end

  def license
    render 'license', layout: 'official_docs'
  end

  def txid_how
    render 'txid_how', layout: 'official_docs'
  end

  def deposit_mock
    render 'deposit_mock', layout: 'official_docs'
  end
end

app/views/documents/api_v2.en.html.slim
.jumbotron
  h2 API version 2
  small Path prefix: /api/v2
  br
  small Response format: JSON

.panel.panel-default
  .panel-heading
    h3 Public/Private API

  .panel-body
    p BitNusa API v2 includes both public API and private API.

  table.table
    thead
      tr
        th Public API
        th Private API
    tbody
      tr
        td No authentication required
        td Authentication required
      tr
        td Unlimited
        td 6000 requests/keypair/5minutes, you can contact BitNusa if you need more.
      tr
        td Ready to use
        td You need to request for access/secret key at first

.panel.panel-default
  .panel-heading
    h3 Authentication

  .panel-body
    p To use private API, you need to get your access/secret key first. After signed up and verified, please visit <a href='/api_tokens'>API Tokens page</a> to get your keys.
    p All private API requires 3 authentication parameters and zero or more API specific parameters. The 3 authentication parameters are:
    table.table
      tr
        td access_key
        td Your access key.
      tr
        td tonce
        td tonce is a timestamp in integer, stands for milliseconds elapsed since <a href='http://en.wikipedia.org/wiki/Unix_epoch'>Unix epoch</a>. Tonce must be within 30 seconds of server's current time. Each tonce can only be used once.
      tr
        td signature
        td Signature of the API request, generated by you, use your secret key.

    p Signature is a hash of the request (in canonical string form):
    pre: code
      | hash = HMAC-SHA256(payload, secret_key).to_hex

    p Payload is a combination of HTTP verb, uri, and query string:
    pre: code
      | # canonical_verb is HTTP verb like GET/POST in upcase.
        # canonical_uri is request path like /api/v2/markets.
        # canonical_query is the request query sorted in alphabetica order, including access_key and tonce, e.g. access_key=xxx&foo=bar&tonce=123456789
        # The combined string looks like: GET|/api/v2/markets|access_key=xxx&foo=bar&tonce=123456789
        def payload
          "\#{canonical_verb}|\#{canonical_uri}|\#{canonical_query}"
        end

    p Note: query parameters are sorted in payload, so it must be "access_key=xxx&foo=bar" not "foo=bar&&access_key=xxx".
    p Suppose my secret key is 'yyy', then the result of HMAC-SHA256 of above payload is:
    pre: code
      | hash = HMAC-SHA256('GET|/api/v2/markets|access_key=xxx&foo=bar&tonce=123456789', 'yyy').to_hex
             = 'e324059be4491ed8e528aa7b8735af1e96547fbec96db962d51feb7bf1b64dee'

    p Now we hav a signed request which can be used like this:
    pre: code
      | curl -X GET 'https://bitnusa.com/api/v2/markets?access_key=xxx&foo=bar&tonce=123456789&signature=e324059be4491ed8e528aa7b8735af1e96547fbec96db962d51feb7bf1b64dee'

.panel.panel-default
  .panel-heading
    h3 Response Format

  .panel-body
    p Corresponding HTTP status code will be used in API response. BitNusa will also return a JSON structure including error details on failed request, for example:
    pre: code
      | {"error":{"code":1001,"message":"market does not have a valid value"}}
    p All errors follow the message format above, only differentiates in code and message. Code is a BitNusa defined error code, indicates the error's category, message is human-readable details.

  .panel-body
    p BitNusa returns HTTP 200 response on successful request, with requested data in JSON format.
    table.table.result
      thead
        tr
          th Data Type
          th Example
          th Comments
      tbody
        tr
          td Market
          td: pre: code
            | {"at":1398410899, "ticker":{"buy":"3000.0","sell":"3100.0","low":"3000.0","high":"3000.0","last":"3000.0","vol":"0.11"}}
          td
            p at: A timestamp in seconds since Epoch
            p buy/sell: Current buy/sell price
            p low/high: Lowest/highest price in last 24 hours
            p last: Last price
            p vol: Trade volume in last 24 hours
        tr
          td Member
          td: pre: code
            | {"sn":"BIN5TFFOGQHTIO","name":"foo","email":"foo@bitnusa.com","activated":true,"accounts":[{"currency":"idr","balance":"100243840.0","locked":"0.0"},{"currency":"btc","balance":"99999708.26","locked":"210.8"}]}
          td
            p sn: Unique identifier of user
            p name: User name
            p email: User email
            p activated: Whether user is activated
            p accounts: User's accounts info, see Account
        tr
          td Account
          td: pre: code
            | {"currency":"idr","balance":"100243840.0","locked":"0.0"}
          td
            p currency: Account type, like 'btc' or 'idr'
            p balance: Account balance, exclude locked funds
            p locked: locked funds
        tr
          td Order
          td: pre: code
            | {"id":7,"side":"sell","price":"3100.0","avg_price":"3101.2","state":"wait","market":"btcidr","created_at":"2014-04-18T02:02:33Z","volume":"100.0","remaining_volume":"89.8","executed_volume":"10.2","trades":[{"id":2,"price":"3100.0","volume":"10.2","market":"btcidr","created_at":"2014-04-18T02:04:49Z","side":"sell"}]}
          td
            p id: Unique order ID
            p side: Buy/Sell
            p price: Order price
            p avg_price: Average execution price
            p state: wait, done or cancel. 'wait' represents the order is active, it may be a new order or partial complete order; 'done' means the order has been fulfilled completely; 'cancel' means the order has been cancelled.
            p market: Which market the order belongs to
            p created_at: Order created time
            p volume: volume to buy/sell
            p remaining_volume: remaining_volume is always less or equal than volume
            p executed_volume: volume = remaining_volume + executed_volume
            p trades: the order's trade history, see Trade. Note: not all order include trades, only detailed order data returned by certain API will.
        tr
          td Trade
          td: pre: code
            | {"id":2,"price":"3100.0","volume":"10.2","market":"btcidr","created_at":"2014-04-18T02:04:49Z","side":"sell"}
          td
            p id: Unique ID
            p price: trade price
            p volume: trade volume
            p market: the market trade belongs to, like 'btcidr'
            p created_at: trade time
        tr
          td OrderBook
          td: pre: code
            | {"asks": [...],"bids": [...]}
          td
            p OrderBook shows orders on market.

.panel.panel-default
  .panel-heading
    h3 Some Examples

  .panel-body
    p Buy 1BTC at price 4000IDR:
    pre: code
      | curl -X POST 'https://bitnusa.com/api/v2/orders' -d 'access_key=your_access_key&tonce=1234567&signature=computed_signature&market=btcidr&price=4000&side=buy&volume=1'

    p Create multiple orders with a single request:
    pre: code
      | curl -X POST 'https://bitnusa.com/api/v2/orders/multi' -d 'access_key=your_access_key&tonce=123456789&signature=computed_signature&market=btcidr&orders[][price]=4000&orders[][side]=sell&orders[][volume]=0.5&orders[][price]=3999&orders[][side]=sell&orders[][volume]=0.99'

.panel.panel-default
  .panel-heading
    h3 Tips/Caveats

  .panel-body
    table.table
      thead
        tr
          th API
          th Detail
      tbody
        tr
          td POST /api/v2/order/delete
          td Cancel order is an asynchronous operation. A success response only means your cancel request has been accepted, it doesn't mean the order has been cancelled. You should always use /api/v2/order or websocket api to get order's latest state.
        tr
          td POST /api/v2/orders/clear
          td Cancel all your orders is an asynchronous operation. A success response only means your request has been accepted. The orders in response may or may not have been cancelled yet.

/.panel.panel-default
  .panel-heading
    h3 Libraries/Tools

  /.panel-body
    ul
      li: h4
        a href='http://github.com/peatio/peatio-client-ruby'
          | peatio-client-ruby (ruby)

.panel.panel-default
  .panel-heading
    h3 API List

  .panel-body
    p All API are listed below with details. Those require access_key/tonce/signature are private API.

.row
  #swagger-ui-container.swagger-ui-wrap

app/views/documents/api_v2.id-ID.html.slim
.jumbotron
  h2 API version 2
  small Path prefix: /api/v2
  br
  small Response format: JSON

.panel.panel-default
  .panel-heading
    h3 Public/Private API

  .panel-body
    p BitNusa API v2 includes both public API and private API.

  table.table
    thead
      tr
        th Public API
        th Private API
    tbody
      tr
        td No authentication required
        td Authentication required
      tr
        td Unlimited
        td 6000 requests/keypair/5minutes, you can contact BitNusa if you need more.
      tr
        td Ready to use
        td You need to request for access/secret key at first

.panel.panel-default
  .panel-heading
    h3 Authentication

  .panel-body
    p To use private API, you need to get your access/secret key first. After signed up and verified, please visit <a href='/api_tokens'>API Tokens page</a> to get your keys.
    p All private API requires 3 authentication parameters and zero or more API specific parameters. The 3 authentication parameters are:
    table.table
      tr
        td access_key
        td Your access key.
      tr
        td tonce
        td tonce is a timestamp in integer, stands for milliseconds elapsed since <a href='http://en.wikipedia.org/wiki/Unix_epoch'>Unix epoch</a>. Tonce must be within 30 seconds of server's current time. Each tonce can only be used once.
      tr
        td signature
        td Signature of the API request, generated by you, use your secret key.

    p Signature is a hash of the request (in canonical string form):
    pre: code
      | hash = HMAC-SHA256(payload, secret_key).to_hex

    p Payload is a combination of HTTP verb, uri, and query string:
    pre: code
      | # canonical_verb is HTTP verb like GET/POST in upcase.
        # canonical_uri is request path like /api/v2/markets.
        # canonical_query is the request query sorted in alphabetica order, including access_key and tonce, e.g. access_key=xxx&foo=bar&tonce=123456789
        # The combined string looks like: GET|/api/v2/markets|access_key=xxx&foo=bar&tonce=123456789
        def payload
          "\#{canonical_verb}|\#{canonical_uri}|\#{canonical_query}"
        end

    p Note: query parameters are sorted in payload, so it must be "access_key=xxx&foo=bar" not "foo=bar&&access_key=xxx".
    p Suppose my secret key is 'yyy', then the result of HMAC-SHA256 of above payload is:
    pre: code
      | hash = HMAC-SHA256('GET|/api/v2/markets|access_key=xxx&foo=bar&tonce=123456789', 'yyy').to_hex
             = 'e324059be4491ed8e528aa7b8735af1e96547fbec96db962d51feb7bf1b64dee'

    p Now we hav a signed request which can be used like this:
    pre: code
      | curl -X GET 'https://bitnusa.com/api/v2/markets?access_key=xxx&foo=bar&tonce=123456789&signature=e324059be4491ed8e528aa7b8735af1e96547fbec96db962d51feb7bf1b64dee'

.panel.panel-default
  .panel-heading
    h3 Response Format

  .panel-body
    p Corresponding HTTP status code will be used in API response. BitNusa will also return a JSON structure including error details on failed request, for example:
    pre: code
      | {"error":{"code":1001,"message":"market does not have a valid value"}}
    p All errors follow the message format above, only differentiates in code and message. Code is a BitNusa defined error code, indicates the error's category, message is human-readable details.

  .panel-body
    p BitNusa returns HTTP 200 response on successful request, with requested data in JSON format.
    table.table.result
      thead
        tr
          th Data Type
          th Example
          th Comments
      tbody
        tr
          td Market
          td: pre: code
            | {"at":1398410899, "ticker":{"buy":"3000.0","sell":"3100.0","low":"3000.0","high":"3000.0","last":"3000.0","vol":"0.11"}}
          td
            p at: A timestamp in seconds since Epoch
            p buy/sell: Current buy/sell price
            p low/high: Lowest/highest price in last 24 hours
            p last: Last price
            p vol: Trade volume in last 24 hours
        tr
          td Member
          td: pre: code
            | {"sn":"BIN5TFFOGQHTIO","name":"foo","email":"foo@bitnusa.com","activated":true,"accounts":[{"currency":"idr","balance":"100243840.0","locked":"0.0"},{"currency":"btc","balance":"99999708.26","locked":"210.8"}]}
          td
            p sn: Unique identifier of user
            p name: User name
            p email: User email
            p activated: Whether user is activated
            p accounts: User's accounts info, see Account
        tr
          td Account
          td: pre: code
            | {"currency":"idr","balance":"100243840.0","locked":"0.0"}
          td
            p currency: Account type, like 'btc' or 'idr'
            p balance: Account balance, exclude locked funds
            p locked: locked funds
        tr
          td Order
          td: pre: code
            | {"id":7,"side":"sell","price":"3100.0","avg_price":"3101.2","state":"wait","market":"btcidr","created_at":"2014-04-18T02:02:33Z","volume":"100.0","remaining_volume":"89.8","executed_volume":"10.2","trades":[{"id":2,"price":"3100.0","volume":"10.2","market":"btcidr","created_at":"2014-04-18T02:04:49Z","side":"sell"}]}
          td
            p id: Unique order ID
            p side: Buy/Sell
            p price: Order price
            p avg_price: Average execution price
            p state: wait, done or cancel. 'wait' represents the order is active, it may be a new order or partial complete order; 'done' means the order has been fulfilled completely; 'cancel' means the order has been cancelled.
            p market: Which market the order belongs to
            p created_at: Order created time
            p volume: volume to buy/sell
            p remaining_volume: remaining_volume is always less or equal than volume
            p executed_volume: volume = remaining_volume + executed_volume
            p trades: the order's trade history, see Trade. Note: not all order include trades, only detailed order data returned by certain API will.
        tr
          td Trade
          td: pre: code
            | {"id":2,"price":"3100.0","volume":"10.2","market":"btcidr","created_at":"2014-04-18T02:04:49Z","side":"sell"}
          td
            p id: Unique ID
            p price: trade price
            p volume: trade volume
            p market: the market trade belongs to, like 'btcidr'
            p created_at: trade time
        tr
          td OrderBook
          td: pre: code
            | {"asks": [...],"bids": [...]}
          td
            p OrderBook shows orders on market.

.panel.panel-default
  .panel-heading
    h3 Some Examples

  .panel-body
    p Buy 1BTC at price 4000IDR:
    pre: code
      | curl -X POST 'https://bitnusa.com/api/v2/orders' -d 'access_key=your_access_key&tonce=1234567&signature=computed_signature&market=btcidr&price=4000&side=buy&volume=1'

    p Create multiple orders with a single request:
    pre: code
      | curl -X POST 'https://bitnusa.com/api/v2/orders/multi' -d 'access_key=your_access_key&tonce=123456789&signature=computed_signature&market=btcidr&orders[][price]=4000&orders[][side]=sell&orders[][volume]=0.5&orders[][price]=3999&orders[][side]=sell&orders[][volume]=0.99'

.panel.panel-default
  .panel-heading
    h3 Tips/Caveats

  .panel-body
    table.table
      thead
        tr
          th API
          th Detail
      tbody
        tr
          td POST /api/v2/order/delete
          td Cancel order is an asynchronous operation. A success response only means your cancel request has been accepted, it doesn't mean the order has been cancelled. You should always use /api/v2/order or websocket api to get order's latest state.
        tr
          td POST /api/v2/orders/clear
          td Cancel all your orders is an asynchronous operation. A success response only means your request has been accepted. The orders in response may or may not have been cancelled yet.

/.panel.panel-default
  .panel-heading
    h3 Libraries/Tools

  /.panel-body
    ul
      li: h4
        a href='http://github.com/peatio/peatio-client-ruby'
          | peatio-client-ruby (ruby)

.panel.panel-default
  .panel-heading
    h3 API List

  .panel-body
    p All API are listed below with details. Those require access_key/tonce/signature are private API.

.row
  #swagger-ui-container.swagger-ui-wrap

app/views/documents/deposit_mock.html.slim
.jumbotron
  h2 Mock Penyetoran pada Development/Staging Server

.panel.panel-default
  table.table
    thead
      tr
        th Mata Uang
        th Link
    tbody
      tr
        td Rupiah (IDR)
        td <a href="https://docs.midtrans.com/en/reference/test.html">https://docs.midtrans.com/en/reference/test.html</a>
      tr
        td Bitcoin (BTC)
        td <a href="https://testnet.coinfaucet.eu/en/">https://testnet.coinfaucet.eu/en/</a>
      tr
        td Ethereum (ETH)
        td <a href="https://faucet.rinkeby.io">https://faucet.rinkeby.io</a>
      tr
        td Litecoin (LTC)
        td <a href="http://testnet.litecointools.com">http://testnet.litecointools.com</a>

app/views/documents/index.html.slim
.panel-body
      = table_for(@docs, class: 'table table-condensed table-hover') do |t|
        - t.column :title, t('.title') , class: 'col-xs-2'
        - t.column :actions, t('.actions'), class: 'col-xs-1' do |x|
          = link_to t('.view'), document_path(x), target: '_blank'

= content_for :guide do
  p.text-warning
    = t('.warning')
    a href="/tickets" = t('.ticket')

app/views/documents/oauth.id-ID.html.slim
.jumbotron
  h2 OAuth Integration

.panel.panel-default
  .panel-heading
    h3 OAuth Authorization

  .panel-body
    p This document describes the flow between 3rd-party application and BitNusa.
.panel.panel-default
  .panel-heading
    h3 OAuth Client Register

  .panel-body
    p To get user authorization through OAuth, your app must be registered on BitNusa.
    p Please contact administrator to register.

.panel.panel-default
  .panel-heading
    h3 Initiate Authorization Request

  .panel-body
    pre: code
      | GET https://bitnusa.com/oauth/authorize?client_id=&lt;your_client_id&gt;&redirect_uri=&lt;registered_rediret_uri&gt;&response_type=code&scope=&lt;scopes&gt;
    p 'scope' is the authorizations you want to request. BitNusa supports 3 scopes:
    ul
      li profile: basic user informations
      li history: user trades history
      li trade: buy/sell on markets
    p e.g. your app want to request for profile and history authorization:
    pre: code
      | scope=profile+history+trade
    p If user grants the authorizations your app requested, BitNusa will generate a auth code and pass it back to redirect_uri.

.panel.panel-default
  .panel-heading
    h3 Get User Token

  .panel-body
    p With auth code, your app can get user token (APIv2 access/secret key) by:
    pre: code
      | POST https://bitnusa.com/oauth/token
    pre: code
      | Params: client_id=&lt;your_client_id&gt;&client_secret=&lt;your_client_secret&gt;&code=&lt;auth_code&gt;&grant_type=authorization_code&redirect_uri=&lt;registered_rediret_uri&gt;
    p After validate the request, BitNusa will return a user token and a refresh token. User token is a string including APIv2 access/secret key, in the format below:
    pre: code
      | &lt;access_key&gt;:&lt;secret_key&gt;
    p Split user token with colon ':', you get APIv2 access/secret key, with which you can access user authorized resources through APIv2.
    p Refresh token is used when user token (APIv2 access/secret key) is expired, please keep it in safe place.
    p For more information about APIv2, please visit <a href='/documents/api_v2'>APIv2 document</a>.

.panel.panel-default
  .panel-heading
    h3 Refresh User Token (APIv2 access/secret key)

  .panel-body
    p The user token you get is valid for 4 hours. When you access user resources with expired user token, BitNusa will return a error message with specific error code 2010:
    pre: code
      | {"error"=>{"code"=>2010, "message"=>"The access key xxxxx has expired."}}
    p When you see this error, get a new user token using the refresh token you got in last step:
    pre: code 
      | POST https://bitnusa.com/oauth/token
    pre: code 
      | Params: client_id=&lt;client_id&gt;&client_secret=&lt;client_secret&gt;&grant_type=refresh_token&refresh_token=&lt;refresh_token&gt;

.panel.panel-default
  .panel-heading
    h3 REMINDER

  .panel-body
    p Do NOT keep any of client id, client secret, or refresh token on user devices. Keep them safe under your control.

.panel.panel-default
  .panel-heading
    h3 References

  .panel-body
    ul
      li http://zh.wikipedia.org/wiki/OAuth
      li http://oauth.net/